services:
  whisper-webui:
    image: mariohuang/whisper-webui
    container_name: whisper-webui
    restart: always
    volumes:
      - ./models:/Whisper-WebUI/models
      - ./outputs:/Whisper-WebUI/outputs
    ports:
      - "7860:7860"
